server:
  port: 8761
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone : http://admin:admin@localhost:${server.port}/eureka/
  instance:
    hostname: peer1
spring:
  application:
    name: cloud-eureka-server
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml