server:
  port: 8775
eureka:
  client:
    service-url:
      defaultZone : http://admin:gimi6532@peer1:8761/eureka/
spring:
  application:
    name: cloud-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  datasource:
      ##本地测试服务器mysql
      url: jdbc:mysql://127.0.0.1:3306/luck_test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123321zZ
      driver-class-name: com.mysql.jdbc.Driver
      dbcp2:
        max-idle: 10
        min-idle: 5
        initial-size: 5
        validation-query: SELECT 1
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 18800
        max-wait-millis: 10000
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
zuul:
  routes:
      user-service:
        path: /api/user/**
        serviceId: user-micro-service-consumer
      order-service:
        path: /api/order/**
        serviceId: order-micro-service-consumer
      web-service:
        path: /api/web/**
        serviceId: web-micro-service-consumer
      baitiao-service:
        path: /api/baitiao/**
        serviceId: baitiao-micro-service-consumer
      pay-service:
        path: /public/**
        serviceId: pay-callback-service-consumer
#断路器配置
hystrix:
  metrics:
    enabled: true
    #刷新间隔
    polling-interval-ms: 2000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 120000
ribbon:
     ConnectTimeout: 3000
     ReadTimeout: 120000